"""
Structured JSON logging for MOI Elasticsearch NLP Query System

Implements JSON Lines format (.jsonl) for machine-readable logs.
Follows constitution principles: reproducibility, observability.
"""

import json
import logging
import os
from datetime import datetime
from typing import Optional


class JSONFormatter(logging.Formatter):
    """
    Custom formatter that outputs logs in JSON format.

    Each log record is formatted as a single-line JSON object with:
    - timestamp: ISO 8601 formatted timestamp
    - level: Log level (INFO, ERROR, etc.)
    - message: Log message
    - Any extra fields passed via logger.info(..., extra={...})
    """

    def format(self, record: logging.LogRecord) -> str:
        """
        Format log record as JSON string.

        Args:
            record: LogRecord to format

        Returns:
            str: JSON-formatted log entry
        """
        log_data = {
            'timestamp': self.formatTime(record, datefmt='%Y-%m-%dT%H:%M:%S.%fZ'),
            'level': record.levelname,
            'message': record.getMessage(),
        }

        # Case 1: Handle record.extra dict (used by log_query_translation)
        if hasattr(record, 'extra') and isinstance(record.extra, dict):
            log_data.update(record.extra)

        # Case 2: Add extra fields from record.__dict__
        # Python logging's extra parameter adds fields directly to the LogRecord object
        reserved_attrs = {
            'name', 'msg', 'args', 'created', 'filename', 'funcName', 'levelname',
            'levelno', 'lineno', 'module', 'msecs', 'message', 'pathname', 'process',
            'processName', 'relativeCreated', 'thread', 'threadName', 'exc_info',
            'exc_text', 'stack_info', 'taskName', 'extra'  # exclude 'extra' itself
        }

        for key, value in record.__dict__.items():
            if key not in reserved_attrs and not key.startswith('_'):
                log_data[key] = value

        return json.dumps(log_data)


def setup_query_translation_logger(log_file_path: str = 'logs/query_translations.jsonl') -> logging.Logger:
    """
    Set up logger for query translation events.

    Creates a logger that writes to JSON Lines format file for:
    - Natural language queries
    - Generated Query DSL
    - Validation results
    - Execution results
    - Performance metrics

    Args:
        log_file_path: Path to log file (default: logs/query_translations.jsonl)

    Returns:
        logging.Logger: Configured logger instance

    Following constitution: All query translations must be logged for reproducibility
    """
    # Create logs directory if it doesn't exist
    log_dir = os.path.dirname(log_file_path)
    if log_dir and not os.path.exists(log_dir):
        os.makedirs(log_dir, exist_ok=True)

    # Create logger
    logger = logging.getLogger('query_translation')
    logger.setLevel(logging.INFO)

    # Remove existing handlers to avoid duplicates
    logger.handlers.clear()

    # Create file handler
    file_handler = logging.FileHandler(log_file_path, mode='a', encoding='utf-8')
    file_handler.setLevel(logging.INFO)

    # Set JSON formatter
    json_formatter = JSONFormatter()
    file_handler.setFormatter(json_formatter)

    # Add handler to logger
    logger.addHandler(file_handler)

    # Prevent propagation to root logger
    logger.propagate = False

    return logger


def log_query_translation(
    logger: logging.Logger,
    nl_query: str,
    index_name: str,
    index_mapping_hash: str,
    prompt: str,
    generated_dsl: str,
    is_valid_json: bool,
    execution_status: str,
    result_count: Optional[int],
    llm_latency_ms: float,
    es_latency_ms: Optional[float],
    total_latency_ms: float,
    llm_model: str,
    llm_temperature: float,
    error_message: Optional[str] = None
) -> None:
    """
    Log a query translation event with full context.

    Args:
        logger: Logger instance
        nl_query: Natural language query input
        index_name: Target Elasticsearch index
        index_mapping_hash: MD5 hash of index mapping (for versioning)
        prompt: Full prompt sent to LLM
        generated_dsl: Query DSL generated by LLM
        is_valid_json: Whether generated DSL is valid JSON
        execution_status: success | validation_failed | execution_failed
        result_count: Number of results from ES (None if failed)
        llm_latency_ms: LLM API response time in milliseconds
        es_latency_ms: ES query execution time in milliseconds (None if failed)
        total_latency_ms: End-to-end latency in milliseconds
        llm_model: LLM model name (e.g., EQuIP_3B)
        llm_temperature: Temperature used for generation
        error_message: Error message if execution failed (optional)

    Following constitution: Log all query context for reproducibility and debugging
    """
    extra = {
        'nl_query': nl_query,
        'index_name': index_name,
        'index_mapping_hash': index_mapping_hash,
        'prompt': prompt,
        'generated_dsl': generated_dsl,
        'is_valid_json': is_valid_json,
        'execution_status': execution_status,
        'result_count': result_count,
        'llm_latency_ms': llm_latency_ms,
        'es_latency_ms': es_latency_ms,
        'total_latency_ms': total_latency_ms,
        'llm_model': llm_model,
        'llm_temperature': llm_temperature,
    }

    if error_message:
        extra['error_message'] = error_message

    # Create a LogRecord with extra fields
    record = logger.makeRecord(
        logger.name,
        logging.INFO,
        fn='',
        lno=0,
        msg='Query translation',
        args=(),
        exc_info=None
    )
    record.extra = extra

    logger.handle(record)
